import Head from 'next/head';
import { PageLayoutMain } from 'source/feature/page-layout/page-layout-main';

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <PageLayoutMain>
        <p>Hello</p>
      </PageLayoutMain>
    </>
  );
}
